### ISSUE TITLE
About the code highlighting

### ISSUE THREAD

**Issue by likair** [Kikobeats/uno-zen#147]
I want to add other languages support, but according to your instruction: 1) go to prismjs.com/download, 2) generate your custom highlight code 3) paste in the prism file 3) compile the assets. 
It still doesn't work.

**Comment by Kikobeats** [comment]
hmmm can you paste terminal error or something to know what happens under the ☔?

**Comment by likair** [comment]
I don't know how to check the terminal error. Have you tired to add more languages support and succeeded? In the prism website, I got .js and .css file, but in your instruction, I just need to modify the _prism.scss?

**Comment by likair** [comment]
What do you mean paste? Is it append or replace?

**Comment by Kikobeats** [comment]
@lebseu replace but is not a direct process. 

You need to adapt the new code because prism default css class match is too specific for ghost code block.
Be careful with the CSS class, use the current code as guide and replace only the style inside the brackets.

I would be grateful with you if you can report me feedback about this to complete the documentation :+1: 

I close the issue but you can still comment here whatever/problem question :-)

**Comment by likair** [comment]
How about prism.js??

**Comment by Kikobeats** [comment]
http://prismjs.com/
