### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by pupboss** [Kikobeats/uno-zen#19]
First, while I was in blog, no matter I click the post or the navigation button, the navigation bar on left always do animate.

And the code in post is a little unpretty, would you like to use [highlight.js](https://highlightjs.org)

**Comment by pupboss** [comment]
About the first problem, I see some people solve by this:

```
if (location.hash && location.hash == "#open") return;
```

But I insert it to uno.js line 721, it does't work.

**Comment by Kikobeats** [comment]
because I try to make possible load fast in mobiles and tablet I'd rather not add another library over the project...If you prefer add it in your fork absolutely you can do it, but simple css for format code is enough IMHO. When I need more I just insert a gist.

About the animation, exists an open issue about it, so I know the problem and will be fixed in the next tagged version :-)
