### ISSUE TITLE
Landing page is blog instead of main Uno Zen landing page

### ISSUE THREAD

**Issue by 16alexanders** [Kikobeats/uno-zen#209]
Example here: alexsikand.io

**Comment by Kikobeats** [comment]
Read docs!

https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#open-button

**Comment by drfraser** [comment]
Hi, hopefully this comment might help someone. Thanks for the theme, BTW, it's nice and saved me a lot of hassle of making my own.

I am having trouble with the splash page / the button on it (e.g. "Blog") not immediately taking the browser to the main page (that shows a list of all posts). I have to hit the button a few times before something gets set properly, apparently - and then the main page is always the one shown (as I'd expect).  I have not yet examined any Javascript code or etc to understand what it is doing and what it should be doing.

I saw this issue and realized how the open button might actually work (I had not done that). My main button on the splash page is called Home so I added the JS about open_button = '.nav-home.... etc.  When I tested this change, the Home button then told the browser to go to http.... /#open which then made sense.  But it still didn't work b/c I hadn't set up Nginx right and it seemed to be dropping the #open or not passing it to the Ghost process...

How should it work? If it should be using #open to indicate 'no more splash page', then I will fix that and figure out what is going on with Ngnix etc. But in case, why it does it take a few button presses before <something> decides to stop showing the entire splash page? Should I be looking at the JS (and where?).  Thanks!   I do need to update to Ghost 1.19 (I'm on 1.17) and I have the latest version of uno-zen

**Comment by drfraser** [comment]
P.S. I am having trouble with the main page displaying the date of posts as 'NAN DAYS AGO'.  Based on what I see re: the timeAgo function, I think it is getting called twice because of the other problem (of needing to push 'Home' multiple times).  i.e. the html value of 'yesterday' is getting treated as a date the second time around.  I was going to file a bug for that, but it is so basic, I figured it wasn't really a general issue

So I'd put some logic in timeAgo to prevent it from redoing things it has already processed.
