### ISSUE TITLE
User must click "Home" button many times before blog opens

### ISSUE THREAD

**Issue by thedch** [Kikobeats/uno-zen#233]
I tried both `<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>` and 

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.6/zepto.min.js"></script>`
`<script>jQuery = Zepto</script>`

in the footer and the problem was still there.

**Comment by drfraser** [comment]
Hi, thedch - how did you solve this?  I am using Zepto 1.2.0...

**Comment by thedch** [comment]
I was unable to solve it and ended up using a different theme. See
https://github.com/thedch/ghost-theme

**Comment by drfraser** [comment]
I got things working, though the underlying problem is not solved. That will require some reworking of code. Here is what I did, for anyone that needs it:

1. In Ghost admin > Design > Navigation

there is usually an entry like 'Home' or 'Blog that is set the root URL of the blog.  That needs '#open' attached to the end, e.g. http://myblog.com/#open

2. Follow the documentation about setting the open_button JS variable. Set it to '.nav-{X} > a' where {X} is the key used in step 1 (e.g. Home or Blog)

Then the button on the splash screen will work properly and also clicking on the blog title (which is a link). The splash screen will roll back or across the whole screen as needed.

The important part is the '#open'. The code, as I can follow it, tries to dynamically add that as needed depending on the current state (current page, location.href etc), but it doesn't quite work. 

There is also some issue with using pace.js and some 1s timeout that manages some animation part, which interferes with the whole process of clicking on Home to get the splash cover to roll back (as far as I can tell). It is not immediately clear what it *should* be doing.
