### ISSUE TITLE
#open issues and no rounded buttons

### ISSUE THREAD

**Issue by julianveerkamp** [Kikobeats/uno-zen#83]
So I just installed the theme. It works fine, except for the navigation buttons. When i click on blog, nothing happens. The URL bar shows http://domain.com/#open but thats it. When I click in the Profile Title name it works like it's supposed to. Also my navigation buttons don't have this nice rounded rectangle around them and some bullet points in front of them.  

While installing the theme with the command you provided in the readme i got an error telling me that "cannot stat node_moduled/uno-zen: no such file or directory". I managed to install the theme by cloning the repo and doing npm install.

**Comment by Kikobeats** [comment]
instead of clone the master branch, download the last tagged version from the [releases](https://github.com/Kikobeats/uno-zen/releases) section because master branch is unstable code and sometimes proof of concept before releases a new version.

The installation script is a little hack to download the last release version as npm dependency and later move in the current directory instead of `node_modules`. I simulated and works fine in my computer but I understand that is not the best solution.

are you linked correctly jQuery in the blog footer of your admin panel? Open JS Console

**Comment by julianveerkamp** [comment]
Moving the HEAD down to the latest relase solved the problem. Thank you very much for your work on the theme and the fast support.
