### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by lalalaring** [Kikobeats/uno-zen#85]
The URL of my blog is: http://www.yanyuhongchen.net/

**Comment by Kikobeats** [comment]
the list of your links in the cover is different from the default provided by the theme. Is it correct?

**Comment by lalalaring** [comment]
ye,i dont know why.i forked it from here,it's different.I corrected it by using npm install now.Please recheck it.

**Comment by Kikobeats** [comment]
I recently released a new version. Can you download `2.5.4` from the
Releases section and replace the code?

**Comment by lalalaring** [comment]
npm version work well now.what version is it?should I must change?you know i must change it to Chinese,i dont want to repeat translating..

**Comment by Kikobeats** [comment]
Better just replace this file in the same path:

https://raw.githubusercontent.com/Kikobeats/uno-zen/master/assets/css/uno-zen.css

**Comment by lalalaring** [comment]
you dont know China policy.Google Facebook etc..is in GFW blacklist...googleapi cant work in China..

**Comment by Kikobeats** [comment]
What do you want to mean? 

I said that just refresh project css/js assets, to the last version, just it!

**Comment by lalalaring** [comment]
or otherwise,the font didn't contain Chinese Charactors..So without CJK System,may can't say anything i dont know

**Comment by lalalaring** [comment]
I said that just refresh project css/js assets, to the last version, just it!

I see..I‘ll Replace It...

**Comment by Kikobeats** [comment]
Oh, now I understood. I think that accidentally you edit the css of and
change the behavior of the list in the cover...

I recommend you see Documentation section in the repository. You can
download the Google font or replace for another browser native and compile
the assets, it should works fine. it's easy.

I'm going to close the issue because the cover don't follow the generic
interface. If you goal setup correctly the cover feel free to open another
issue and I will add it :-)

**Comment by lalalaring** [comment]
ok
